// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.639
package widgets

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

// import openAPI "github.com/UnseenBook/spacetraders-go-sdk"
func NavWidget() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container\" id=\"widget-content\"><section id=\"selections\"><select name=\"ship-select\" id=\"ship-select\"><option value=\"ship1\">Ship 1</option> <option value=\"ship2\">Ship 2</option> <option value=\"ship3\">Ship 3</option></select> <button><span class=\"material-symbols-outlined\">rocket</span> Select Ship</button> <select name=\"waypoint-select\" id=\"waypoint-select\"><option value=\"waypoint1\">Waypoint 1</option> <option value=\"waypoint2\">Waypoint 2</option> <option value=\"waypoint3\">Waypoint 3</option></select> <button><span class=\"material-symbols-outlined\">compass_calibration</span> Select Waypoint</button></section><section id=\"ship-details\"><div id=\"ship-info\"><span class=\"material-symbols-outlined\">rocket</span><div id=\"ship-info-text\"><p>Ship Name</p><p>Ship Type</p><meter min=\"0\" low=\"10\" max=\"100\" high=\"90\" optimum=\"70\" value=\"56\">Fuel</meter> <meter min=\"0\" low=\"60\" max=\"100\" high=\"90\" optimum=\"90\" value=\"95\">Durability</meter></div></div><div id=\"ship-state\"><span class=\"material-symbols-outlined\">compass_calibration</span><div id=\"ship-state-text\"><p>Location</p><p>IN_TRANSIT</p></div></div></section><section class=\"row\" id=\"waypoint-details\"><div id=\"waypoint-info\"><div id=\"environment-details\"><p>Waypoint Name</p><p>Orbits</p><p>Coordinates</p><p>Faction</p><p>Charted By</p><p>Charted Date</p></div><div id=\"trait-details\"><p>Trait Name</p><p>Description</p></div></div><div id=\"route-info\"><p>Route details including the distance between the 2 points, and the amount of time required to complete the journey. This will be passed in.</p><button>Confirm</button> <button>Decline</button></div></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
