// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID              int32
	Accountid       pgtype.Text
	Symbol          pgtype.Text
	HeadQuarters    pgtype.Text
	Credits         pgtype.Int4
	StartingFaction pgtype.Text
	ShipCount       pgtype.Int4
}

type ApiKey struct {
	ID  int32
	Key pgtype.Text
	UID pgtype.Text
}

type Player struct {
	ID        int32
	UserUid   pgtype.Text
	Username  pgtype.Text
	Password  pgtype.Text
	Email     pgtype.Text
	CreatedAt pgtype.Timestamp
}
