// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package mysql

import (
	"database/sql"
)

type Agent struct {
	ID              int32
	Accountid       sql.NullString
	Symbol          sql.NullString
	HeadQuarters    sql.NullString
	Credits         sql.NullInt32
	StartingFaction sql.NullString
	ShipCount       sql.NullInt32
}

type ApiKey struct {
	ID     int32
	ApiKey sql.NullString
	UID    sql.NullString
}

type Faction struct {
	ID             int32
	Symbol         sql.NullString
	WaypointSymbol sql.NullString
}

type Orbital struct {
	ID             int32
	Symbol         sql.NullString
	WaypointSymbol sql.NullString
}

type Player struct {
	ID        int32
	UserUid   sql.NullString
	Username  sql.NullString
	Password  sql.NullString
	Email     sql.NullString
	CreatedAt sql.NullTime
}

type System struct {
	ID           int32
	Symbol       sql.NullString
	SectorSymbol sql.NullString
	Type         sql.NullString
	X            sql.NullInt32
	Y            sql.NullInt32
}

type Waypoint struct {
	ID           int32
	SystemSymbol sql.NullString
	Symbol       sql.NullString
	Type         sql.NullString
	X            sql.NullInt32
	Y            sql.NullInt32
	Orbits       sql.NullString
}
