// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package mysql

import (
	"context"
	"database/sql"
)

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO
    api_keys (api_key, u_id)
SELECT ?, user_uid
FROM players
WHERE
    username = ?
`

type CreateAPIKeyParams struct {
	ApiKey   sql.NullString
	Username sql.NullString
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKey, arg.ApiKey, arg.Username)
	return err
}

const createSystem = `-- name: CreateSystem :exec
INSERT INTO
    systems (
        symbol, sector_symbol, type, x, y
    )
VALUES (?, ?, ?, ?, ?)
`

type CreateSystemParams struct {
	Symbol       sql.NullString
	SectorSymbol sql.NullString
	Type         sql.NullString
	X            sql.NullInt32
	Y            sql.NullInt32
}

func (q *Queries) CreateSystem(ctx context.Context, arg CreateSystemParams) error {
	_, err := q.db.ExecContext(ctx, createSystem,
		arg.Symbol,
		arg.SectorSymbol,
		arg.Type,
		arg.X,
		arg.Y,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO
    players (
        user_uid, username, password, email, created_at
    )
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	UserUid   sql.NullString
	Username  sql.NullString
	Password  sql.NullString
	Email     sql.NullString
	CreatedAt sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.UserUid,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.CreatedAt,
	)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, user_uid, username, password, email, created_at FROM players
`

func (q *Queries) GetAll(ctx context.Context) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.UserUid,
			&i.Username,
			&i.Password,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOneByUsername = `-- name: GetOneByUsername :exec
SELECT id, user_uid, username, password, email, created_at FROM players WHERE username = ?
`

func (q *Queries) GetOneByUsername(ctx context.Context, username sql.NullString) error {
	_, err := q.db.ExecContext(ctx, getOneByUsername, username)
	return err
}

const getSystemBySymbol = `-- name: GetSystemBySymbol :exec
SELECT id, symbol, sector_symbol, type, x, y FROM systems WHERE symbol = ?
`

func (q *Queries) GetSystemBySymbol(ctx context.Context, symbol sql.NullString) error {
	_, err := q.db.ExecContext(ctx, getSystemBySymbol, symbol)
	return err
}

const getUserWithAPIKeyByUsername = `-- name: GetUserWithAPIKeyByUsername :one
SELECT pl.id, pl.user_uid, pl.username, pl.password, pl.email, pl.created_at, ak.api_key
FROM players pl
    JOIN api_keys ak ON pl.user_uid = ak.u_id
WHERE
    pl.username = ?
`

type GetUserWithAPIKeyByUsernameRow struct {
	ID        int32
	UserUid   sql.NullString
	Username  sql.NullString
	Password  sql.NullString
	Email     sql.NullString
	CreatedAt sql.NullTime
	ApiKey    sql.NullString
}

func (q *Queries) GetUserWithAPIKeyByUsername(ctx context.Context, username sql.NullString) (GetUserWithAPIKeyByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserWithAPIKeyByUsername, username)
	var i GetUserWithAPIKeyByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.UserUid,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.CreatedAt,
		&i.ApiKey,
	)
	return i, err
}
